## https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually
name: importable_name 
channels:      ## Add any other channels below if necessary
- conda-forge
dependencies:  
- python=3.11
- nvidia/label/cuda-12.1.0::cuda  # for syntax guide, see https://conda.io/projects/conda/en/latest/user-guide/concepts/pkg-search.html
- nvidia/label/cuda-12.1.0::cuda-toolkit  
- conda
- ipython
- ipykernel
- jupyter
- numpy
- matplotlib
- scipy
- pip
- pre-commit
- black
- nbstripout
- pycodestyle
- pydocstyle
- pytest
- pytest-cov
- pytest-xdist
- pyprojroot
- python-dotenv
########################################################################
# Note: remainder is copied into temp requirements.txt file, then run with pip. 
# All valid flags after `pip install -U ...` will work. See code at:
# https://github.com/conda/conda/blob/435d7e40859a1cc74c05814899cdc24818002150/conda_env/installers/pip.py#L41
########################################################################
- pip:
  ########################################################################
  # How to identify compatible jaxlib wheel using platform compatibility tag:
  # (See https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#platform-compatibility-tags)
  # Platform tag format is  {python tag}-{abi tag}-{platform tag}.
  # CPython 311 Application Binary Interface -> cp311 
  # CUDA major version 12 -> cuda12
  # CuDNN major version 8.8 -> cudnn88
  # linux_x86_64 architecture -> manylinux2014_x86_64 (see PEP 599, 600)
  ########################################################################
  # --- see https://github.com/google/jax#installation, and
  #     https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
  - https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.7+cuda12.cudnn88-cp311-cp311-manylinux2014_x86_64.whl
  # --- see https://pypi.org/project/nvidia-cudnn-cu12/
  - nvidia-cudnn-cu12==8.8.1.3
  - jax==0.4.8
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - mknotebooks
